FROM docker.io/bitnami/spark:3.3

USER root

# 폴더 생성
RUN mkdir -p /opt/bitnami/spark/work-dir

# requirements.txt 파일을 Docker 이미지 내의 /opt/bitnami/spark/work-dir 폴더로 복사
COPY ./requirements.txt /opt/bitnami/spark/work-dir/

WORKDIR /opt/bitnami/spark/work-dir/

# requirements.txt에 명시된 패키지들 설치
RUN pip install --no-cache-dir -r requirements.txt
