name: Continuous Integration and Deployment

on:
  push:
    branches: [ feat/add-hajun ]
  workflow_dispatch:

jobs:
  
  build_and_upload:
    name: Build and Upload to S3
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Archive Repository
        run: tar cvfz RecruitRadar.tar.gz *

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-northeast-2

      - name: Upload Archive to S3
        run: |
          aws s3 cp RecruitRadar.tar.gz s3://de1-1-backend/backend_folder/

      - name: Deploy with AWS CodeDeploy
        run: |
          aws deploy create-deployment \
          --application-name de1-1-backend \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --deployment-group-name aws-fastapi-group \
          --s3-location bucket=de1-1-backend,bundleType=tgz,key=backend_folder/RecruitRadar.tar.gz
  
  deploy_to_ec2:
    name: Deploy to EC2
    needs: build_and_upload
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: SSH and Deploy on EC2
        uses: appleboy/ssh-action@v0.1.4  # Using a specific version for stability
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/scraper_server
            chmod 777 ./Dockerfile
            chmod 777 ./docker-compose.yml
            docker-compose up -d