name: TEST

on:
  workflow_dispatch:
  push:
    branches: [ feat/add-hajun2 ]

env:
  APP_ENV: test

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Setup Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      # Install Dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scraper_server/requirements.txt
          pip install pytest-cov  

      # Prepare for Coverage Report
      - name: Create Coverage Report Directory
        run: mkdir -p htmlcov

      # Run Tests
      - name: Test Code
        env:
          TESTING: true
        run: |
          pytest --cov=your_package --cov-report html:htmlcov


      # Zip and Upload Coverage Report as an Artifact
      - name: Zip Coverage Report
        run: zip -r report.zip htmlcov/


      - name: Upload Coverage Report
        uses: actions/upload-artifact@v2
        with:
          name: CoverageReport
          path: report.zip